- README.md
- src/PimpMyREPL.jl
- src/bracket_inserter.jl
- src/passes/SyntaxHighlighter.jl
- src/repl.jl
- src/repl_pass.jl
- Precompilable
- Should highlight when pressing up and down
> add precompilation and highlighting for search

- docs/src/features/error_messages.md
- src/ErrorMessages.jl
- src/OhMyREPL.jl
- src/errormessage_overrides.jl
- src/output_prompt_overwrite.jl
- src/passes/SyntaxHighlighter.jl
- src/passes/colorschemes.jl
- src/prompt.jl
- src/repl.jl
- src/repl_pass.jl
Maybe you can try this @fredrikekre just to see things look ok on another computer.
> fixes for 0.6

- src/OhMyREPL.jl
Seems to work ok, cc @joshbode
> only load OhMyREPL in interactive mode

- test/runtests.jl
this restores whatever the previous value (or unset) was when finished
> set FORCE_COLOR in runtests.jl using withenv

- docs/src/features/syntax_highlighting.md
Sorry, forgot to document the color scheme. I think this is the only important place.
> Document Tomorrow Night Bright schemes

- src/passes/SyntaxHighlighter.jl
- src/passes/colorschemes.jl
> add tomorrow colorscheme

- src/OhMyREPL.jl
Fixes OhMyREPL not loading in VSCode
> relax when not injecting hotkeys

- src/passes/SyntaxHighlighter.jl
> color NaN as number

- src/MarkdownHighlighter.jl
ref https://github.com/JuliaLang/julia/pull/25293
> fix Markdown rendering

- src/logger_core.jl
Docs prob need a matching comment added
> Disable automatic log overwriting until #141 is resolved.

- src/MarkdownHighlighter.jl
@iblis17 could you explain the rationale behind the `occursin(r"jldoctest;?", "jldoctest")` statement?
> fix markdown highlighting

- src/MarkdownHighlighter.jl
- src/repl.jl
> fix unicode handling in helpmode

- docs/src/features/syntax_highlighting.md
- src/passes/SyntaxHighlighter.jl
- src/passes/colorschemes.jl
Added the popular OneDark theme to match vim, tmux, etc...
> added onedark theme

- src/repl.jl
Fixes #177, fixes #176, fixes #172, fixes #164.
> fix some string indexing errors

- src/BracketInserter.jl
- src/passes/SyntaxHighlighter.jl
> Don't add closing quote after right bracket

- src/OhMyREPL.jl
Fix https://github.com/KristofferC/OhMyREPL.jl/issues/183
> fix initing interface if not yet inited

- .travis.yml
- docs/Manifest.toml
- src/repl.jl
- test/runtests.jl
> remove wrong overloads for Ctrl-N, Ctrl-P

- docs/src/features/prompt.md
- src/output_prompt_overwrite.jl
- src/prompt.jl
> allow using functions for prompt modifications

- src/repl.jl
- xref: https://github.com/JuliaLang/julia/pull/36689
> fix errors on v1.6

- src/passes/SyntaxHighlighter.jl
Now also colors e.g. `0b11110000`, `0o755` and `0xff`
> Add bin/oct/hex int syntax highlighting

- src/passes/SyntaxHighlighter.jl
- src/passes/colorschemes.jl
> add GruvBox dark

- docs/src/features/fzf.md
Added description of some of the keys I discovered by accident. I suspect FZF supports even more but I think in particular the multiselect using TAB is worth mentioning here.
> Describe fuzzy search keyboard and mouse commands

- .github/workflows/CI.yml
- Project.toml
- src/OhMyREPL.jl
This makes the first key pretty much instant for me.
Closes https://github.com/KristofferC/OhMyREPL.jl/issues/242, https://github.com/KristofferC/OhMyREPL.jl/issues/286
Replaces https://github.com/KristofferC/OhMyREPL.jl/pull/288
> add a precompile workload

- src/OhMyREPL.jl
- src/repl.jl
Fix https://github.com/KristofferC/OhMyREPL.jl/issues/269, #166
> reinsert keybinds after Pkg

- src/OhMyREPL.jl
- src/refresh_lines.jl
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/295
> fix coloring when scrolling through history

- src/prompt.jl
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/299
> only override prompts if they have been changed

- Project.toml
- src/FakePTYs.jl
- src/OhMyREPL.jl
- src/precompile.jl
@johnnychen94, can you try this?
> change precompile strategy to FakePTYs

- src/repl.jl
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/310
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/125
> only syntax highlight the julia prompt

- src/repl.jl
Adds tab completion hints that landed in https://github.com/JuliaLang/julia/pull/51229
> Show tab complete hints, if supported
