src/ErrorMessages.jl, src/errormessage_overrides.jl
This changes the default error messages to what @pabloferz suggested in https://github.com/JuliaLang/julia/pull/18228#issuecomment-245882983:
For those of you who like the new line before the file name and line number there is a new `ENV` variable `JULIA_ERR_LINFO_NEWLINE` which if set will print like the previous way:
I am in progress of writing docs for all the options and stuff.
=> update error messages

src/errormessage_overrides.jl
`is` is now deprecated on julia-0.6, https://github.com/JuliaLang/julia/pull/18978.
=> Replace is with ===

src/errormessage_overrides.jl
Fixes same error as here: https://github.com/JuliaLang/julia/pull/18726.
There is one more showerror which did not like the `:limit => true` addition: https://github.com/KristofferC/OhMyREPL.jl/blob/91779c695104bc6e768edebc1ad92e7016948a0d/src/errormessage_overrides.jl#L26 Not sure why this is.
=> Limit error message length

src/passes/SyntaxHighlighter.jl, test/test_highlighter.jl
Previously function call syntax would override macro highlighting when using an opening `(`. (Note sure of what the best way to check for this was, so if you've got a better approach that would be good.)
=> Highlight macro with parentheses correctly

src/passes/SyntaxHighlighter.jl, src/passes/colorschemes.jl
This is a first pass - the colors are the closest I could get using `Colors.colordiff` with the function referenced in #63 - it surprisingly does not look very bright, though. This is how it looks in iTerm2 (for the Mac):
=> Add tomorrow night bright color scheme

src/ErrorMessages.jl, test/test_bracketmatch.jl, test/test_custompass.jl, test/test_highlighter.jl
otherwise you're assuming the dependencies have done so, which isn't guaranteed to always be the case
=> add using Compat for take!

src/repl.jl
This appears to be needed to make the Home key work again. Otherwise I get:
```
ERROR (in the keymap): MethodError: no method matching buffer(::Base.AbstractIOBuffer{Array{UInt8,1}})
Closest candidates are:
buffer(::Base.LineEdit.PrefixSearchState) at LineEdit.jl:1596
buffer(::Base.LineEdit.SearchState) at LineEdit.jl:1595
buffer(::Base.LineEdit.PromptState) at LineEdit.jl:1594
...
Stacktrace:
[1] (::OhMyREPL.Prompt.##10#37)(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL, ::String) at /home/kristoffer/.julia/v0.6/OhMyREPL/src/repl.jl:87
[2] (::Base.LineEdit.##13#14{OhMyREPL.Prompt.##10#37,String})(::Base.LineEdit.MIState, ::Base.REPL.LineEditREPL) at ./LineEdit.jl:740
[3] prompt!(::Base.Terminals.TTYTerminal, ::Base.LineEdit.ModalInterface, ::Base.LineEdit.MIState) at …
```
=> add noop for buffer of IOBuffer

src/OhMyREPL.jl
Should be somewhat less error-prone, to only hide exactly the expected warnings instead of every possible problem that might be going to stderr at load time.
=> Show any unexpected stderr output during __init__

src/passes/SyntaxHighlighter.jl, src/passes/colorschemes.jl
I use this colorscheme in VIM. Its still very different in subtle ways (like $myvar interpolation and such), but it looks pretty close.
=> add colorscheme: Distinguished

src/OhMyREPL.jl
This makes more sense to me than the current behaviour, which totally prevents loading when Julia is started with `julia -i -e "blah"`. The other possible option I see is to force loading OhMyREPL via an environment variable or providing an API to init it, but those seem more cumbersome than this change.
=> Always load if Julia is started with -i -e

src/MarkdownHighlighter.jl, src/OhMyREPL.jl
* fix enable_highlight_markdown to work, fixes #110 
* changes the julia prompt in doctests to red to better work with light backgrounds
cc @goerz, do you still believe a setting for the markdown prompt color is needed, now when red is the default?
=> markdown fixes

src/passes/SyntaxHighlighter.jl
fixes coloring of `1:b`, `1.0:b`, `(1+2):b`, `a:b` (#181)
but not `1 :b`
=> fix coloring of a:b

docs/src/features/syntax_highlighting.md, src/passes/SyntaxHighlighter.jl, src/passes/colorschemes.jl
Adds the Material Darker color scheme by [Nate Peters](https://github.com/ntpeters/base16-materialtheme-scheme) derived from the [Base16](https://github.com/chriskempson/base16) theme architecture.
Added under the name `"Base16MaterialDarker"`.
=> Add Base16 Material Darker color scheme

src/BracketInserter.jl, src/OhMyREPL.jl, src/passes/SyntaxHighlighter.jl
Merged #191 and a fix to #192 .
I relaxed the cases where we would obtain a quote pairing.
Instead of telling it when to pair i changed it to when not to.
Easier to read and more flexible in my opinion.
I tested many edge cases, triple quoting works as now, but i can't say i tested every scenario.
=> Proper matching, and backtick support.

src/BracketInserter.jl
Potential fix for #200. Added condition such that transposing expressions `foo'`,  `foo_'` or `[1 2 3]'` does not autocomplete the `'`.
The bracket around `v == '\'' && occursin(r"\w|\]", string(left_peek))` is more for readability, not really needed due to operator precedence, feel free to change/remove.
=> fixing transpose expressions

src/repl.jl
Closes #137.
This should also future-proof OhMyREPL against future changes to the abort behaviour of the standard REPL. :relaxed:
=> Confirm on exit

docs/src/features/fzf.md, src/OhMyREPL.jl, src/repl.jl
Reason probably is that if you do full screen windows terminal would clear the buffer.
=> update Fzf for windows experience

src/OhMyREPL.jl
Fixes #222 when `using OhMyREPL` is in `startup.jl`.
=> Fix issue 222.

src/passes/colorschemes.jl
This is closer to Monokai in Sublime Text or VS Code, also more legible
(before => after)
for reference, in VS Code:
=> Fix Monokai themes

src/repl.jl
Fixes https://github.com/KristofferC/OhMyREPL.jl/issues/236
cc @colinxs
=> unset fzf env variable when calling fzf

docs/src/features/syntax_highlighting.md, src/passes/SyntaxHighlighter.jl, src/passes/colorschemes.jl
Adds three of GitHub's [colorschemes](https://primer.style/primitives/colors#themes), matching the [VS Code themes](https://github.com/primer/github-vscode-theme/):
=> Add GitHub colorschemes

src/BracketInserter.jl, src/passes/BracketHighlighter.jl
In REPL, backspace will delete active region.
I changed to make it behaves the same.
#283
=> change backspaces behave on active region

src/OhMyREPL.jl, src/passes/RainbowBrackets.jl, src/passes/SyntaxHighlighter.jl
a more thorough check would be better but I guess this would be the job of Crayons.jl (ref https://github.com/KristofferC/Crayons.jl/issues/15)
based on my testing, support is here starting from julia 1.5.3, even though it only appears in the [1.6 NEWS](https://github.com/JuliaLang/julia/blob/v1.6.0-beta1/NEWS.md?plain=1#L237) (PR is not linked, I don't know where exactly it was fixed)
=> default to 256 color with julia1.5.3 and later on windows

src/passes/SyntaxHighlighter.jl, src/passes/colorschemes.jl
This is an updated version of a very old PR I had for adding this.  [Dracula](https://github.com/dracula/dracula-theme) is a popular color scheme implemented on a bewildering variety of software.  It would be great to have this in OhMyREPL so that I can finally take it out of my `startup.jl` :slightly_smiling_face:
=> added Dracula color scheme

src/OhMyREPL.jl
some users have reported OhMyREPL getting stuck precompiling, this should fix this in a non-ideal way
=> kill precompilation process if it is too slow

Project.toml, docs/Manifest.toml, docs/src/internals/passes.md, src/MarkdownHighlighter.jl, src/OhMyREPL.jl, src/passes/BracketHighlighter.jl, src/passes/RainbowBrackets.jl, src/passes/SyntaxHighlighter.jl, src/precompile.jl, src/repl.jl, src/repl_pass.jl, test/test_bracketmatch.jl, test/test_custompass.jl, test/test_highlighter.jl
JuliaSyntax.jl is the future of Julia parsing in Julia so it makes sense to start using that over Tokenize.jl that will likely be deprecated.
=> move to JuliaSyntax.jl over Tokenize.jl

Project.toml, docs/Manifest.toml, docs/src/internals/passes.md, src/MarkdownHighlighter.jl, src/OhMyREPL.jl, src/passes/BracketHighlighter.jl, src/passes/RainbowBrackets.jl, src/passes/SyntaxHighlighter.jl, src/repl.jl, src/repl_pass.jl, test/test_custompass.jl, test/test_highlighter.jl
Going through the parser allows us to be more precise and complete.
For example it automatically:
* Determines when contextual keywords are keywords, vs identifiers. For example, the `outer` in `outer = 1` is an identifier, but a keyword in `for outer i = 1:10`
* Validates numeric literals (eg, detecting overflow cases like `10e1000` and flagging as errors)
* Splits or combines ambiguous tokens. For example, making the `...` in `import ...A` three separate `.` tokens.
Also uses `is_error` to detect error tokens and highlight them with the error color.
Requires https://github.com/JuliaLang/JuliaSyntax.jl/pull/221
As I was writing this, I noticed that the syntax highlighter has some heuristics in it to act a bit like a parser (just a very little bit!).  For example, highlighting quoted …
=> Use post-parse `JuliaSyntax.tokenize()` API

src/MarkdownHighlighter.jl
This PR makes OhMyREPL match exactly [the default Markdown formatting of the stdlib](https://github.com/JuliaLang/julia/blob/1b183b93f4b78f567241b1e7511138798cea6a0d/stdlib/Markdown/src/render/terminal/render.jl#L105C1-L113C4) when `OhMyREPL.HIGHLIGHT_MARKDOWN[] == false`.
Formatted code in REPL help is then a bit more compact, with the downside that it might be a tad harder to make the difference between the output of a code example and text.
Before:
```julia
julia> using Markdown
julia> md"""
A
```julia
function a() end
```
B
"""
A
function a() end
B
julia> using OhMyREPL
julia> md"""
A
```julia
function a() end
```
B
"""
A
function a() end
B
```
After:
```julia
julia> using Markdown, OhMyREPL
julia> md"""
A
```julia
function a() end
```
B
"""
A
function a() end
B
```
=> Remove traling newline in Markdown code blocks

src/OhMyREPL.jl
this was the case before #304
it breaks my `startup.jl`, where I modified the colorscheme using the returned value
=> return active colorscheme after `colorscheme!`

src/repl.jl
Uses the current REPL line as the initial query string for fzf. If fzf returns an empty result, inserts the initial line instead of the empty string.
=> Small fzf search QOL update.

src/repl.jl
Fix #349 corresponding to https://github.com/JuliaLang/julia/pull/54674
https://github.com/JuliaLang/julia/pull/54674/files#diff-730f90e0bf9ca018477a1d4a52e0d7398af2bb8cf9e401568fd86690eec81bb7L1453-R1488
=> Fix moving up and down in REPL

Project.toml, src/repl.jl
Don't really understand the change that was made as I didn't look into it, but suffice it to say it's possible for `repl.mistate` to be defined but `nothing`.  In such a case it doesn't have the field `interface` and so OhMyREPL crashes on the next line.  This adds a check for whether that field is `nothing` and does whatever it would do if it weren't defined.  Not 100% confident this is the intended behavior but seems to work fine.  I suspect that the `isdefined(repl,:mistate)` can be removed entirely, but I really don't know, so I left it in.
=> fix crash when repl.mistate is defined but nothing

src/MarkdownHighlighter.jl
Fix #357 corresponding to https://github.com/JuliaLang/julia/pull/51928
where `Markdown.lines` has been removed:
https://github.com/JuliaLang/julia/blob/3a35aec36d13c3e651c97bac664da2e778d591ad/stdlib/Markdown/src/render/terminal/formatting.jl#L10
=> Fix Markdown print error in `1.12.0-DEV`

src/repl.jl
=> fix JLFzf loading

src/repl.jl
Fixes #362.
Working locally on Julia 1.10.4, 1.9.4, 1.8.5 on my Linux machine.
=> fix disappearing fzf matches

src/MarkdownHighlighter.jl
When choosing whether to highlight in `julia` or `julia-repl`, this now checks whether the code block has REPL blocks (`julia>`).  If it does, it goes to `julia-repl` highlighting, otherwise it goes to `julia` highlighting.
Fix #293
=> Fix `jldoctest` blocks without `julia>` not getting rendered
